services:
  postgres:
    image: postgres:17

    container_name: connected-music-postgres

    restart: always

    environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: connected-music-db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./backend:/usr/src/app
  #     - /usr/src/app/node_modules
